# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'NakedEye3D' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NakedEye3D
	pod 'DeviceKit'
end
